//file:noinspection
plugins {
	id 'fabric-loom' version '1.6-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = "${project.archives_base_name}-fabric"
}

repositories {
	maven {
		name = 'Mod Menu'
		url = 'https://maven.terraformersmc.com/releases'
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()

	modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modImplementation "com.terraformersmc:modmenu:${project.mod_menu_version}"
}

loom {
	accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")
	mixin {
		defaultRefmapName.set("${mod_id}.refmap.json")
	}
}

processResources {
	def expandProps = [
		"java_version_range": java_version_range,
		"minecraft_version": minecraft_version,
		"minecraft_version_range": minecraft_version_range,
		"fabric_loader_version": fabric_loader_version,
		"fabric_loader_version_range": fabric_loader_version_range,
		"fabric_version": fabric_version,
		"mod_id": mod_id,
		"mod_name": mod_name,
		"mod_author": mod_author,
		"mod_version": mod_version,
		"mod_icon": mod_icon,
		"mod_license": mod_license,
		"mod_description": mod_description,
		"mod_repo": mod_repo,
	]

	filesMatching(['fabric.mod.json', '*.mixins.json']) {
		expand expandProps
	}
	inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}
