org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Common
minecraft_version=1.21.10
minecraft_version_range=[1.21.10,)

# Forge
forge_loader_version_range=[60,)
forge_version=60.0.11
forge_version_range=[60,)
mapping_channel=official
mapping_version=1.21.10

## Mod Properties
mod_id=potioncauldron
mod_name=Potion Cauldron
mod_author=Maxoduke
mod_version=1.0.2+mc1.21.10
mod_icon=icon.png
mod_license=MIT
mod_description=A feature from Bedrock edition
mod_repo=https://github.com/maxoduke/Potion-Cauldron
mod_group_id=dev.maxoduke.mods
jar_name=potion-cauldron