# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Common
java_version_range=>=25
minecraft_version=26.2
minecraft_version_range=>=26.2

# Fabric Properties
fabric_loader_version=0.19.3
fabric_loader_version_range=>=0.19.3
fabric_api_version=0.154.2+26.2
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_id=potioncauldron
mod_name=Potion Cauldron
mod_author=Maxoduke
mod_version=1.0.2+mc26.2
mod_icon=icon.png
mod_license=MIT
mod_description=A feature from Bedrock edition
mod_repo=https://github.com/maxoduke/Potion-Cauldron
maven_group=dev.maxoduke.mods
archives_base_name=potioncauldron
jar_name=potion-cauldron

# Dependencies
mod_menu_version=20.0.1
