# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Common
java_version_range=>=21
minecraft_version=1.21
minecraft_version_range=>=1.21

# Fabric Properties
fabric_loader_version=0.15.11
fabric_loader_version_range=>=0.15.11
fabric_version=0.100.1+1.21

# Mod Properties
mod_id=potioncauldron
mod_name=Potion Cauldron
mod_author=Maxoduke
mod_version=1.0.1+mc1.21
mod_icon=icon.png
mod_license=MIT
mod_description=A feature from Bedrock edition
mod_repo=https://github.com/maxoduke/Potion-Cauldron
maven_group=dev.maxoduke.mods
archives_base_name=potioncauldron
jar_name=potioncauldron-fabric

# Dependencies
mod_menu_version=11.0.0-rc.2
